# fly.toml app configuration file generated for helldivers2-loadout-randomizer on 2025-05-31T00:53:45-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "helldivers2-loadout-randomizer"
primary_region = "dfw"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
